In [11]:
import numpy as np


matriz = []
print('Matriz 4x4: ')
for l in range(1, 5):
    linha = []
    for c in range(1, 5):
        novonumero = int(input(f'Escolha o número que ocupará a posição {l}; {c} na matriz.'))
        linha.append(novonumero)
    else:
        matriz.append(linha)

matriz = np.array(matriz)
matrizv2 = np.asmatrix(matriz)

print(matrizv2)


## hoje eu to brincante prof






Matriz 4x4: 
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [35]:
import numpy as np
acimadadiag = []

matriz = []
print('Matriz 4x4: ')
for l in range(1, 5):
    linha = []
    for c in range(1, 5):
        novonumero = int(input(f'Escolha o número que ocupará a posição {l}; {c} na matriz.'))
        linha.append(novonumero)
    else:
        matriz.append(linha)


for linha in range(4):
    for coluna in range(4):
        if coluna > linha:
            acimadadiag.append(matriz[linha][coluna])
else:
    sumresult = sum(acimadadiag)

print('Matriz Criada: ')
matriz = np.array(matriz)
matrizv2 = np.asmatrix(matriz)
print(matrizv2)

print()

print('Números acima da diagonal principal: ')
print(acimadadiag)

print()

print('Soma dos números acima da diagonal principal: ')
print(sumresult)

##esse aqui eu suei bonito






Matriz 4x4: 
Matriz Criada: 
[[1 2 3 4]
 [5 1 2 3]
 [4 5 1 2]
 [3 4 5 1]]

Números acima da diagonal principal: 
[2, 3, 4, 2, 3, 2]

Soma dos números acima da diagonal principal: 
16


In [36]:
for linha in matriz3:
    for valor in linha:
        print(f'{valor:02}', end=' ')
    print(f'')

30 36 51 59 36 
13 40 100 33 10 
38 02 16 44 57 


In [12]:


matriz=[
    [15, 30, 21],
    [79, 27, 44],
    [12, 70, 25]
]

print(f'{matriz[1][2]}')

44


In [51]:
import random as r

matriz3 = []
for i in range(4) :
    linha = []
    for j in range(4):
        elemento = r.randint(0, 100)
        linha.append(elemento)
    matriz3.append(linha)

for linha in matriz3:
    for valor in linha:
        print(f'{valor:02}', end=' ')
    print(f'')

for i in matriz3:
    print(i)


35 04 46 73 
53 45 61 50 
64 31 48 27 
23 72 43 41 
[35, 4, 46, 73]
[53, 45, 61, 50]
[64, 31, 48, 27]
[23, 72, 43, 41]


In [53]:
import random as r
diagsecundaria = []
counter = 0
for linha in matriz3:
    diagsecundaria.append(linha[1 * counter])
    counter = counter + 1

print('A matriz 3 é:')
for linha in matriz3:
    for valor in linha:
        print(f'{valor:02}', end=' ')
    print(f'')

print('Sua diagonal secundária é composta de: ')
print(diagsecundaria)

print(f'A soma dos elementos de sua diagonal secundária é {sum(diagsecundaria)}.')







A matriz 3 é:
35 04 46 73 
53 45 61 50 
64 31 48 27 
23 72 43 41 
Sua diagonal secundária é composta de: 
[35, 45, 48, 41]
A soma dos elementos de sua diagonal secundária é 169.


In [38]:
for i in range(3):
    for j in range(3):
        print(f'Elemento ({i}, {j}) >>> {matriz3[i][j]}')

Elemento (0, 0) >>> 30
Elemento (0, 1) >>> 36
Elemento (0, 2) >>> 51
Elemento (1, 0) >>> 13
Elemento (1, 1) >>> 40
Elemento (1, 2) >>> 100
Elemento (2, 0) >>> 38
Elemento (2, 1) >>> 2
Elemento (2, 2) >>> 16


In [61]:
##Exercício 4

matriz4 = []
print('Matriz 4x4: ')
for l in range(1, 5):
    linha = []
    for c in range(1, 5):
        novonumero = int(input(f'Escolha o número que ocupará a posição {l}; {c} na matriz.'))
        linha.append(novonumero)
    else:
        matriz4.append(linha)

maior = []
for linha in matriz4:
    newvalue = max(linha)
    maior.append(newvalue)


print('A matriz é: ')
for linha in matriz4:
    for coluna in linha:
        print(f'{coluna:02}', end=' ')
    print()
print()
counter = 1
for n in maior:
    print(f'O maior número na linha {counter} é {n}.')
    counter += 1



    

Matriz 4x4: 
A matriz é: 
01 02 03 04 
05 06 07 08 
09 01 02 03 
04 05 06 07 

O maior número na linha 1 é 4.
O maior número na linha 2 é 8.
O maior número na linha 3 é 9.
O maior número na linha 4 é 7.


In [65]:
##Exercício 5
matriz5 = []
pares = []

print('Matriz 4x4: ')
for l in range(1, 5):
    linha = []
    for c in range(1, 5):
        novonumero = int(input(f'Escolha o número que ocupará a posição {l}; {c} na matriz.'))
        linha.append(novonumero)
    else:
        matriz5.append(linha)

for linha in matriz5:
    for coluna in linha:
        if coluna % 2 == 0:
            pares.append(coluna)

print('Matriz:')
for line in matriz5:
    print(line)
print(f'Dentre estes, os números pares são {pares}, totalizando {len(pares)}: ')



Matriz 4x4: 
Matriz:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 1, 2, 3]
[4, 5, 6, 7]
Dentre estes, os números pares são [2, 4, 6, 8, 2, 4, 6], totalizando 7: 


In [1]:
##Exercício 6
valuemultip = int(input('Digite o número que multiplicará a matriz: '))
matriz6 = []
matriz6v2 = []
print('Matriz 4x4: ')
print(f'Número que multiplica a matriz: {valuemultip}')
for l in range(1, 5):
    linha = []
    for c in range(1, 5):
        novonumero = int(input(f'Escolha o número que ocupará a posição {l}; {c} na matriz.'))
        linha.append(novonumero)
    else:
        matriz6.append(linha)
print('Matriz inicial:')
for linha in matriz6:
    print(linha)

for linha in matriz6:
    linhanova = []
    for coluna in linha:
        vezdois = coluna * valuemultip
        linhanova.append(vezdois) 
    else:
        matriz6v2.append(linhanova)
print()
print('Matriz multiplicada:')
print(matriz6v2)


    

Matriz 4x4: 
Número que multiplica a matriz: 4
Matriz inicial:
[1, 2, 3, 1]
[2, 3, 1, 2]
[3, 1, 2, 3]
[1, 2, 3, 1]

Matriz multiplicada:
[[4, 8, 12, 4], [8, 12, 4, 8], [12, 4, 8, 12], [4, 8, 12, 4]]
